services:
  inventario:
    build:
      context: ./microservizi/magazzino/inventario
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net-magazzino
    environment:
      - PORT=3000
      - WAREHOUSE_ID=1
      - MONGO_URL=mongodb://mongo:27017/inventory
    volumes:
      - ./microservizi/magazzino/inventario/src:/usr/src/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - net-magazzino
    volumes:
      - ./microservizi/mongo_db:/docker-entrypoint-initdb.d

  inventario-aggregato:
    build:
      context: ./microservizi/cloud/inventario_aggregato
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    networks:
      - net-magazzino
    environment:
      - PORT=3010
      - ID_MAGAZZINO=1
      - MONGO_URL=mongodb://mongo:27017/inv_aggregato_db
    volumes:
      - ./microservizi/cloud/inventario_aggregato/src:/usr/src/app/src
    depends_on:
      - mongo

  nats:
     image: nats:latest
     ports:
       - "4222:4222"
       - "8222:8222"
     command: ["--jetstream", "-VV", "-m", "8222"]
     networks:
       - net-magazzino
     

  api-gateway:
    build: 
      context: ./microservizi/api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080" # Gateway API
    environment:
      - PORT=8080
      - NATS_URL=nats://nats:4222
    networks:
      - net-magazzino
    volumes:
      - ./microservizi/api_gateway:/usr/src/app/src
    depends_on:
      - inventario
      - nats

networks:
  net-magazzino:
    driver: bridge


