services:
  inventario:
    build:
      context: ./microservizi/magazzino/inventario
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net-magazzino
    environment:
      - PORT=3000
      - ID_MAGAZZINO=1
      - MONGO_URL=mongodb://mongo:27017/inventory
    volumes:
      - ./microservizi/magazzino/inventario/src:/usr/src/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - net-magazzino
    volumes:
      - ./microservizi/magazzino/mongo_db:/docker-entrypoint-initdb.d

  inventario-aggregato:
    build:
      context: ./microservizi/cloud/inventario_aggregato
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    networks:
      - net-magazzino
    environment:
      - PORT=3010
      - ID_MAGAZZINO=1
      - MONGO_URL=mongodb://mongo-aggregatore:27017/inventario
    volumes:
      - ./microservizi/cloud/inventario_aggregato/src:/usr/src/app/src
    depends_on:
      - mongo

  mongo-aggregatore:
    image: mongo:latest
    container_name: mongo-aggregatore
    ports:
      - "27018:27017"
    networks:
      - net-magazzino
    volumes:
      - ./microservizi/magazzino/mongo_db:/docker-entrypoint-initdb.d

networks:
  net-magazzino:
    driver: bridge

  #    depends_on:
  #      - nats-inventario

  #--------------------------------------#

  # inventario-a:
  #   build: ./MagazzinoA/inventario-a
  #   image: swe/inventario-a
  #   ports:
  #     - "8080:3000"
  #   networks:
  #     - net-magazzino
  # ordini-a:
  #   build: ./MagazzinoA/ordini-a
  #   image: swe/ordini-a
  #   ports:
  #     - "8081:3000"
  #   networks:
  #     - net-magazzino
  # nats-inventario:
  #   image: nats:latest
  #   ports:
  #     - "4222:4222"
  #   networks:
  #     - net-magazzino
