services:
  inventario:
    container_name: inventario
    build: 
      context: ./microservizi/magazzino/inventario
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net-magazzino
    environment:
      - PORT=3000
      - WAREHOUSE_ID=1
      - MONGO_URL=mongodb://mongo:27017/inventory
    volumes:
      - ./microservizi/magazzino/inventario/src:/usr/src/app/src
    depends_on:
      - mongo

  ordini:
    container_name: ordini
    build: 
      context: ./microservizi/magazzino/ordini
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - net-magazzino
    environment:
      - PORT=3000
      - ID_MAGAZZINO=1
      - MONGO_URL=mongodb://mongo:27017/inventory
    volumes:
      - ./microservizi/magazzino/ordini/src:/usr/src/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - net-magazzino
    volumes:
      - ./microservizi/magazzino/mongo_db:/docker-entrypoint-initdb.d

  nats:
     container_name: nats
     image: nats:latest
     ports:
       - "4222:4222"
     command:
       - "--jetstream"
     networks:
       - net-magazzino

  api-gateway:
    container_name: api-gateway
    build: 
      context: ./microservizi/api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Gateway API
    environment:
      - PORT=8080
      - NATS_URL=nats://nats:4222
    networks:
      - net-magazzino
    volumes:
      - ./microservizi/api_gateway:/usr/src/app/src
    depends_on:
      - inventario
      - nats

networks:
  net-magazzino:    
    driver: bridge

  #--------------------------------------#

  # inventario-a:
  #   build: ./MagazzinoA/inventario-a
  #   image: swe/inventario-a
  #   ports:
  #     - "8080:3000"
  #   networks:
  #     - net-magazzino
  # ordini-a:
  #   build: ./MagazzinoA/ordini-a
  #   image: swe/ordini-a
  #   ports:
  #     - "8081:3000"
  #   networks:
  #     - net-magazzino


