version: '3.8'

services:
  nats:
    image: nats
    ports:
      - "4222:4222"

  ordini:
    build:
      context: ./ordini
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  inventario:
    build:
      context: ./inventario
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
