version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  ordini:
    image: magazzinoa-ordini
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  inventario:
    image: magazzinoa-inventario
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
